// <auto-generated />
using System;
using MiPrimerWebAPI_M3.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MiPrimerWebAPI_M3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210213233230_Libro")]
    partial class Libro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiPrimerWebAPI_M3.Entities.Autor", b =>
                {
                    b.Property<int>("iIdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iIdAutor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("MiPrimerWebAPI_M3.Entities.Libro", b =>
                {
                    b.Property<int>("iIdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AutoriIdAutor")
                        .HasColumnType("int");

                    b.Property<string>("cTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("iIdAutor")
                        .HasColumnType("int");

                    b.HasKey("iIdLibro");

                    b.HasIndex("AutoriIdAutor");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("MiPrimerWebAPI_M3.Entities.Libro", b =>
                {
                    b.HasOne("MiPrimerWebAPI_M3.Entities.Autor", "Autor")
                        .WithMany("lstLibros")
                        .HasForeignKey("AutoriIdAutor");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("MiPrimerWebAPI_M3.Entities.Autor", b =>
                {
                    b.Navigation("lstLibros");
                });
#pragma warning restore 612, 618
        }
    }
}
